import { useState } from "react";
import { Link } from "react-router-dom";
import { Footer } from "../components/Footer";

const topNavLinks = [
  { label: "Products", href: "#products" },
  { label: "House Construction", to: "/house-builders" },
  { label: "Find Professionals", to: "/find-agent" },
  { label: "Inspirations", to: "/inspiration" },
  { label: "More", to: "/more" },
  { label: "Post Your Ad", to: "/post-ad", accent: true },
];

const requestColumns = [
  { label: "City / Town ?", placeholder: "E.g. Piliyandala" },
  { label: "Type of property", placeholder: "Residential or Commercial" },
  { label: "Leasing or purchasing", placeholder: "Via a Loan or Cash Purchase" },
  { label: "Billing scheme", placeholder: "Net Metering / Net Plus / Net Accounting" },
];

const steps = [
  "Submit your details",
  "Our team will get in touch with you to gather further information",
  "Your details will be provided to selected solar providers",
  "Each company will evaluate your requirements and contact you separately",
  "Schedule a site survey with our selected provider(s)",
  "Receive your proposal",
  "Get Solar rooftop installed",
];

const providerCards = [
  {
    slug: "green-smart-solutions",
    name: "GreenSmart Solutions Pvt Ltd",
    image: "https://images.unsplash.com/photo-1497440001374-f26997328c1b?w=1200&q=80&auto=format&fit=crop",
    description:
      "GreenSmart Solutions (Pvt) Ltd is a leading solar energy solutions provider in Sri Lanka with over 10 years of industry experience. Based in Gampaha, the company specializes in solar installations for homes and businesses.",
  },
  {
    slug: "aurora-energy-systems",
    name: "Aurora Energy Systems",
    image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=1200&q=80&auto=format&fit=crop",
    description:
      "Aurora Esystems (Pvt) Ltd is a Sri Lankan company providing innovative solar energy solutions for homes, businesses, and industries. Specializing in grid-tied, off-grid, and hybrid systems.",
  },
  {
    slug: "jlanka-technologies",
    name: "JLanka Technologies",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80&auto=format&fit=crop",
    description:
      "JLanka Technologies (Pvt) Ltd is a leading renewable energy solutions provider in Sri Lanka, specializing in the design, supply, installation, and maintenance of solar power systems.",
  },
];

const systemTypes = [
  {
    title: "Grid-connected Solar Rooftop PV System",
    text: "This solar system is linked to the network through a meter system that measures energy consumption and does not have a backup bank.",
  },
  {
    title: "Off-grid Solar Panel",
    text: "The only component of this solar system is a battery bank. It is ideal for remote or rural locations.",
  },
  {
    title: "Hybrid Plant Solar System",
    text: "This sort of solar system generates solar energy while also providing backup power in the event of a power outage.",
  },
];

const schemeCards = [
  {
    title: "Net Metering",
    text: "Install rooftop solar PV systems and connect them to the national electricity network. Export and import are measured by the utility meter, and the bill credits exports against imports.",
    idealFor: "Residential households and factories with high energy consumption and small roof space.",
  },
  {
    title: "Net Accounting",
    text: "Excess energy generated by roof-mounted solar panels is paid as an export tariff. If consumption exceeds generation, the customer pays the existing electricity tariff for the excess energy.",
    idealFor: "Warehouses or factories that have a large roof space and generate excess power.",
  },
  {
    title: "Net Plus",
    text: "The solar PV electricity generation is exported through a dedicated meter, while energy import is measured separately and billed at the existing tariff.",
    idealFor: "Solar farms, landlords, and buildings with very little consumption that want to export all generated power.",
  },
];

const faqItems = [
  [
    "How does Idealhome help people switch to solar energy?",
    "We connect you with trusted solar energy providers so you can request quotes and compare prices from different providers.",
  ],
  [
    "What are the benefits of switching to solar energy?",
    "Lower energy bills, reduced carbon footprint, and increased property value are among the main benefits.",
  ],
  [
    "How much does it cost to install solar panels?",
    "The cost depends on the system size, quality of the panels, and installation complexity. Providers can give you a customised quote.",
  ],
  [
    "Do you offer financing options for solar installations?",
    "Yes. Financing options, including loans and leases, are available through our solar partners.",
  ],
  [
    "How do I know if my property is suitable for solar panels?",
    "Roof angle, shading, and available space affect the result. Our providers can evaluate the property and recommend the best option.",
  ],
  [
    "What is Net Metering?",
    "Net Metering allows rooftop solar users to export power to the grid and get credited for the energy supplied.",
  ],
];

const cities = [
  "Colombo",
  "Gampaha",
  "Dehiwala",
  "Wattala",
  "Nugegoda",
  "Kandy",
  "Galle",
  "Jaffna",
  "Kalutara",
  "Matara",
  "Kurunegala",
  "Mount Lavinia",
  "Malabe",
  "Piliyandala",
  "Maharagama",
  "Battaramulla",
  "Rajagiriya",
  "Negombo",
  "Pannipitiya",
  "Kotte",
  "Homagama",
  "Kottawa",
  "Kadawatha",
];

const tips = [
  {
    title: "Do Solar Panels Need Cleaning?",
    summary: "Regular cleaning helps keep panels efficient by removing dust, debris, and bird droppings.",
  },
  {
    title: "How Much Direct Sunlight Do Solar Panels Need?",
    summary: "Panels work best with strong sunlight, but modern systems can still generate power in mixed conditions.",
  },
  {
    title: "How to Build a Solar Panel",
    summary: "Solar panel systems are typically designed and installed by professionals to match the roof and energy load.",
  },
  {
    title: "How Much Power Does A Solar Panel Produce?",
    summary: "Production depends on panel type, sunlight hours, and system size. A provider can estimate your expected output.",
  },
  {
    title: "How Do Clouds Affect Solar Panels?",
    summary: "Cloud cover reduces output, but solar systems can still produce usable power on cloudy days.",
  },
  {
    title: "How do solar panels work?",
    summary: "Solar panels convert sunlight into electricity that can be used at home or exported to the grid.",
  },
  {
    title: "How Many kWh Does A Solar Panel Produce Per Day?",
    summary: "Daily output depends on the system size, roof space, and weather conditions in your area.",
  },
  {
    title: "How to Pick the Best Solar Panels?",
    summary: "Choose based on efficiency, warranty, roof fit, and the reputation of the installer.",
  },
  {
    title: "Do I Need to Add Grounding to My Solar Installation?",
    summary: "Grounding is an important safety measure and should be handled according to the installer’s design.",
  },
  {
    title: "How to Profit From Solar Energy",
    summary: "Savings and grid export options can help solar owners reduce bills and improve long-term returns.",
  },
  {
    title: "Wind vs Solar Energy",
    summary: "Solar is usually a better fit for rooftops and homes, while wind depends on different site conditions.",
  },
];

const relatedServices = [
  {
    title: "Movers",
    text: "Relocate with ease - efficient, safe, and reliable moving services for residential and commercial clients.",
    href: "/our-services",
  },
  {
    title: "Construction",
    text: "Build your dream home with our expert house construction services - quality workmanship and attention to detail guaranteed.",
    href: "/house-builders",
  },
  {
    title: "Solar",
    text: "Go green with our solar services - expert design, installation, and maintenance of solar panel systems for your home or business.",
    href: "#hero",
  },
  {
    title: "Home loan calculator",
    text: "Calculate your estimated monthly home loan payment.",
    href: "/home-loans/calculator",
  },
  {
    title: "Get Assistance with buying or selling",
    text: "One stop solution for all your property needs.",
    href: "/our-services",
  },
  {
    title: "Market Insights",
    text: "Market reports, estimation tools and stats about the property market.",
    href: "/market-insights",
  },
];

export default function SolarPanelsPage() {
  const [step, setStep] = useState(0);
  const [submitted, setSubmitted] = useState(false);
  const [selectedProvider, setSelectedProvider] = useState(0);
  const [selectedTip, setSelectedTip] = useState(0);
  const [form, setForm] = useState({
    city: "",
    propertyType: "Residential",
    purchaseType: "Via a Loan",
    billingScheme: "Net Metering",
    usage: "",
    name: "",
    email: "",
    phone: "",
  });

  const updateField = (field, value) => {
    setForm((current) => ({ ...current, [field]: value }));
  };

  const handleSubmit = (event) => {
    event.preventDefault();
    setSubmitted(true);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-slate-50 text-slate-900">
      <header className="sticky top-0 z-40 border-b border-slate-200 bg-white/97 shadow-sm backdrop-blur-md">
        <div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-3 px-4 py-4 md:px-8">
          <Link to="/" className="flex items-center gap-2 rounded-lg bg-gradient-to-r from-blue-600 to-blue-700 px-3 py-2 font-black text-white shadow-md hover:shadow-lg transition">
            <span className="text-lg">🏠</span>
            <div className="leading-none">
              <div className="text-sm font-black">Lanka</div>
              <div className="text-xs font-bold">Property</div>
            </div>
          </Link>

          <nav className="flex flex-wrap items-center gap-2 text-xs font-bold uppercase tracking-wide text-slate-700 md:gap-4">
            {topNavLinks.map((item) =>
              item.to ? (
                <Link
                  key={item.label}
                  to={item.to}
                  className={`rounded-lg px-3 py-2 transition font-semibold ${item.accent ? "bg-gradient-to-r from-blue-600 to-blue-700 text-white shadow-md hover:shadow-lg" : "hover:bg-slate-100"}`}
                >
                  {item.label}
                </Link>
              ) : (
                <a key={item.label} href={item.href} className="rounded-lg px-3 py-2 transition font-semibold hover:bg-slate-100">
                  {item.label}
                </a>
              )
            )}
            <span className="rounded-lg border border-slate-300 px-3 py-2 text-slate-600 font-semibold">EN</span>
          </nav>
        </div>
      </header>

      <section id="hero" className="relative overflow-hidden text-white">
        <div className="absolute inset-0 bg-gradient-to-br from-blue-900 via-blue-800 to-slate-900" />
        <img
          src="https://images.unsplash.com/photo-1509391366360-2e959784a276?w=1600&q=80&auto=format&fit=crop"
          alt="Solar rooftop"
          className="absolute inset-0 h-full w-full object-cover opacity-30"
        />
        <div className="absolute inset-0 bg-gradient-to-t from-blue-950/80 via-blue-900/60 to-transparent" />
        <div className="relative mx-auto grid min-h-[720px] max-w-7xl gap-10 px-4 py-12 md:px-8 lg:grid-cols-[1.1fr_0.9fr] lg:items-center">
          <div className="max-w-2xl pt-20 lg:pt-0">
            <div className="inline-block rounded-full bg-white/15 px-4 py-2 backdrop-blur-sm mb-4">
              <span className="text-xs font-bold uppercase tracking-wider text-white/90">Solar Energy Solutions</span>
            </div>
            <h1 className="mt-4 text-5xl font-black leading-tight tracking-tight md:text-6xl lg:text-7xl text-white drop-shadow-lg">
              Power Your Home with Solar
            </h1>
            <p className="mt-6 max-w-xl text-xl leading-relaxed text-white/95 drop-shadow-sm">
              Connect with trusted solar providers, compare quotes, and save up to 50% on your electricity bills with professional installation.
            </p>
            <div className="mt-8 flex flex-wrap gap-4">
              <button onClick={() => document.querySelector('form')?.scrollIntoView({ behavior: 'smooth' })} className="rounded-lg bg-white px-6 py-3 text-sm font-black text-blue-900 transition hover:shadow-xl hover:scale-105">
                Get Your Free Quote
              </button>
              <Link to="/help" className="rounded-lg border-2 border-white px-6 py-3 text-sm font-black text-white transition hover:bg-white/10">
                Learn More
              </Link>
            </div>
          </div>

          <form onSubmit={handleSubmit} className="rounded-2xl bg-white/95 backdrop-blur-sm p-6 text-slate-900 shadow-2xl md:p-8">
            <p className="text-xs font-bold uppercase tracking-wider text-blue-600">Quick Quote Request</p>
            <div className="mt-6 flex items-center justify-center gap-3">
              <span className={`h-3 w-3 rounded-full transition ${step === 0 ? "bg-gradient-to-r from-blue-600 to-blue-500 shadow-lg" : "border-2 border-blue-200 bg-white"}`} />
              <span className="h-px w-12 border-t-2 border-blue-200" />
              <span className={`h-3 w-3 rounded-full transition ${step === 1 ? "bg-gradient-to-r from-blue-600 to-blue-500 shadow-lg" : "border-2 border-blue-200 bg-white"}`} />
            </div>

            {step === 0 ? (
              <>
                <h2 className="mt-6 text-xl font-black text-slate-800">Tell us about your property</h2>
                <div className="mt-5 grid gap-4">
                  {requestColumns.map((field) => (
                    <label key={field.label} className="block">
                      <span className="mb-2 block text-sm font-bold text-slate-700">{field.label}</span>
                      <input
                        className="w-full rounded-lg border border-slate-300 px-4 py-3 text-sm font-medium outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-200 transition"
                        placeholder={field.placeholder}
                        value={field.label === "City / Town ?" ? form.city : field.label === "Type of property" ? form.propertyType : field.label === "Leasing or purchasing" ? form.purchaseType : form.billingScheme}
                        onChange={(event) => {
                          if (field.label === "City / Town ?") updateField("city", event.target.value);
                          if (field.label === "Type of property") updateField("propertyType", event.target.value);
                          if (field.label === "Leasing or purchasing") updateField("purchaseType", event.target.value);
                          if (field.label === "Billing scheme") updateField("billingScheme", event.target.value);
                        }}
                      />
                    </label>
                  ))}

                  <label className="block">
                    <span className="mb-2 block text-sm font-bold text-slate-700">Average Monthly Electricity Usage</span>
                    <div className="flex gap-2 rounded-lg border border-slate-300 p-2">
                      {[
                        ["LKR", "Rs: 0.00"],
                        ["UNITS", "0"],
                      ].map(([label, placeholder]) => (
                        <button
                          key={label}
                          type="button"
                          className="rounded-lg border border-blue-300 bg-blue-50 px-3 py-2 text-xs font-bold text-blue-700 transition hover:bg-blue-100"
                        >
                          {label}
                        </button>
                      ))}
                      <input
                        className="min-w-0 flex-1 rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-200"
                        placeholder="Rs: 0.00"
                        value={form.usage}
                        onChange={(event) => updateField("usage", event.target.value)}
                      />
                    </div>
                  </label>
                </div>

                <button
                  type="button"
                  onClick={() => setStep(1)}
                  className="mt-6 ml-auto block rounded-lg bg-gradient-to-r from-blue-600 to-blue-700 px-8 py-3 text-sm font-bold text-white transition hover:shadow-lg hover:scale-105"
                >
                  Continue →
                </button>
              </>
            ) : (
              <>
                <h2 className="mt-3 text-xl font-black text-slate-800">Your contact information</h2>
                <div className="mt-5 grid gap-4">
                  {[
                    ["Your name", "name"],
                    ["Email address", "email"],
                    ["Contact number", "phone"],
                  ].map(([label, field]) => (
                    <label key={label} className="block">
                      <span className="mb-2 block text-sm font-bold text-slate-700">{label}</span>
                      <input
                        className="w-full rounded-lg border border-slate-300 px-4 py-3 text-sm font-medium outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-200 transition"
                        placeholder={label}
                        value={form[field]}
                        onChange={(event) => updateField(field, event.target.value)}
                      />
                    </label>
                  ))}
                </div>

                {submitted && (
                  <div className="mt-4 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700 shadow-sm">
                    ✓ Thanks! Your solar request has been received. We'll contact you shortly.
                  </div>
                )}

                <div className="mt-6 flex items-center justify-between gap-3">
                  <button
                    type="button"
                    onClick={() => setStep(0)}
                    className="rounded-lg border-2 border-slate-300 px-6 py-3 text-sm font-bold text-slate-700 transition hover:bg-slate-50"
                  >
                    ← Back
                  </button>
                  <button
                    type="submit"
                    className="rounded-lg bg-gradient-to-r from-blue-600 to-blue-700 px-8 py-3 text-sm font-bold text-white transition hover:shadow-lg hover:scale-105"
                  >
                    Send Request
                  </button>
                </div>
              </>
            )}
          </form>
        </div>
      </section>

      <section className="mx-auto max-w-7xl px-4 py-16 md:px-8">
        <div className="grid gap-8 rounded-2xl bg-white p-8 shadow-lg border border-slate-100 lg:grid-cols-[0.95fr_1.05fr] lg:items-center">
          <div>
            <h2 className="text-4xl font-black tracking-tight text-slate-900 md:text-5xl">Save Big with Solar Energy</h2>
            <p className="mt-4 text-lg leading-8 text-slate-600">
              Lower electricity bills, reduce your carbon footprint, and increase your property value with professional solar installation.
            </p>
          </div>
          <div className="grid gap-4 sm:grid-cols-3">
            {[
              "Save up to 50% on electricity bills",
              "Expert quotes from trusted providers",
              "Easy loan & financing options available",
            ].map((item) => (
              <div key={item} className="rounded-xl bg-gradient-to-br from-blue-50 to-blue-100 p-5 text-sm font-semibold leading-7 text-slate-800 border border-blue-200">
                <span className="mr-3 text-lg text-blue-600">✓</span>
                {item}
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="mx-auto max-w-7xl px-4 py-16 md:px-8">
        <div className="space-y-6">
          <div>
            <div className="inline-block rounded-full bg-blue-100 px-4 py-2 mb-3">
              <span className="text-xs font-bold uppercase tracking-wider text-blue-700">How It Works</span>
            </div>
            <h2 className="text-4xl font-black text-slate-900">Our 7-Step Process</h2>
          </div>
          <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">
            {steps.map((stepText, index) => (
              <div key={stepText} className="rounded-xl bg-white p-6 shadow-md border border-slate-100 hover:shadow-lg hover:border-blue-200 transition group">
                <div className="mb-4 inline-flex h-10 w-10 items-center justify-center rounded-full bg-gradient-to-br from-blue-600 to-blue-700 text-sm font-black text-white group-hover:scale-110 transition">
                  {index + 1}
                </div>
                <p className="text-sm font-semibold leading-7 text-slate-700">{stepText}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section id="residential" className="mx-auto max-w-7xl px-4 py-16 md:px-8">
        <div className="grid gap-8 overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-lg lg:grid-cols-[1fr_1fr] lg:items-center">
          <div className="p-8 md:p-12">
            <h2 className="text-4xl font-black text-slate-900">Residential Solar</h2>
            <h3 className="mt-3 text-lg font-semibold text-slate-600">Perfect for homeowners looking to save on energy bills</h3>
            <div className="mt-6 flex flex-wrap gap-3">
              <Link to="/our-services/solar-panels#types" className="rounded-lg border border-slate-300 bg-white px-5 py-3 text-sm font-bold text-slate-700 hover:bg-slate-50 transition">
                System Types
              </Link>
              <Link to="/our-services/solar-panels#faq" className="rounded-lg bg-gradient-to-r from-blue-600 to-blue-700 px-5 py-3 text-sm font-bold text-white hover:shadow-lg transition">
                View More
              </Link>
            </div>
          </div>
          <img
            src="https://images.unsplash.com/photo-1509391366360-2e959784a276?w=1400&q=80&auto=format&fit=crop"
            alt="Residential solar"
            className="h-full min-h-[400px] w-full object-cover"
          />
        </div>
      </section>

      <section id="industrial" className="mx-auto max-w-7xl px-4 py-16 md:px-8">
        <div className="grid gap-8 overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-lg lg:grid-cols-[1fr_1fr] lg:items-center">
          <img
            src="https://images.unsplash.com/photo-1509390495902-6d0b7f1c2e4c?w=1400&q=80&auto=format&fit=crop"
            alt="Industrial solar"
            className="h-full min-h-[400px] w-full object-cover"
          />
          <div className="p-8 md:p-12">
            <h2 className="text-4xl font-black text-slate-900">Industrial Solar</h2>
            <p className="mt-3 text-lg font-semibold text-slate-600">Save up to 50% on energy bills for warehouses and factories</p>
            <ul className="mt-6 space-y-3 text-sm font-semibold leading-7 text-slate-700">
              <li className="flex items-start gap-3"><span className="text-blue-600 text-lg">✓</span> Reduce costs by 50% annually</li>
              <li className="flex items-start gap-3"><span className="text-blue-600 text-lg">✓</span> Payback period: 3-4 years (ROI)</li>
              <li className="flex items-start gap-3"><span className="text-blue-600 text-lg">✓</span> Multiple scheme options available</li>
            </ul>
            <div className="mt-8 flex flex-wrap gap-3">
              <Link to="/home-loans/calculator" className="rounded-lg bg-gradient-to-r from-blue-600 to-blue-700 px-5 py-3 text-sm font-bold text-white hover:shadow-lg transition">
                Calculate Savings
              </Link>
              <Link to="/market-insights" className="rounded-lg border border-slate-300 bg-white px-5 py-3 text-sm font-bold text-slate-700 hover:bg-slate-50 transition">
                Market Insights
              </Link>
            </div>
          </div>
        </div>
      </section>

      <section id="products" className="mx-auto max-w-7xl px-4 py-16 md:px-8">
        <div>
          <div className="inline-block rounded-full bg-blue-100 px-4 py-2 mb-3">
            <span className="text-xs font-bold uppercase tracking-wider text-blue-700">Our Providers</span>
          </div>
          <h2 className="text-4xl font-black text-slate-900">Featured Solar Providers</h2>
          <p className="mt-2 text-slate-600 font-semibold">Choose from trusted, verified solar installation companies</p>
        </div>

        <div className="mt-8 grid gap-6 md:grid-cols-3">
          {providerCards.map((provider, index) => (
            <article key={provider.name} className={`overflow-hidden rounded-2xl border-2 bg-white shadow-lg transition hover:shadow-2xl hover:scale-105 ${selectedProvider === index ? "border-blue-600 ring-2 ring-blue-200" : "border-slate-100"}`}>
              <div className="flex h-64 items-center justify-center bg-slate-100 overflow-hidden">
                <img src={provider.image} alt={provider.name} className="h-full w-full object-cover" />
              </div>
              <div className="p-6">
                <h3 className="text-xl font-black text-slate-900">{provider.name}</h3>
                <p className="mt-3 text-sm leading-7 text-slate-600">{provider.description}</p>
                <Link
                  to={`/our-services/solar-panels/${provider.slug}`}
                  onClick={() => setSelectedProvider(index)}
                  className="mt-5 inline-flex w-full justify-center rounded-lg border-2 border-blue-600 bg-white px-4 py-3 text-sm font-bold text-blue-600 transition hover:bg-blue-50"
                >
                  View Details →
                </Link>
              </div>
            </article>
          ))}
        </div>
      </section>

      <section id="provider-details" className="mx-auto max-w-7xl px-4 py-16 md:px-8">
        <div className="rounded-2xl bg-white p-8 shadow-lg border border-slate-100 md:p-12">
          <div className="inline-block rounded-full bg-blue-100 px-4 py-2 mb-3">
            <span className="text-xs font-bold uppercase tracking-wider text-blue-700">Provider Selection</span>
          </div>
          <h2 className="mt-3 text-4xl font-black text-slate-900">Choose Your Solar Provider</h2>
          <div className="mt-8 grid gap-4 lg:grid-cols-3">
            {providerCards.map((provider, index) => (
              <button
                key={provider.name}
                type="button"
                onClick={() => setSelectedProvider(index)}
                className={`rounded-xl border-2 p-6 text-left transition font-semibold ${selectedProvider === index ? "border-blue-600 bg-blue-50" : "border-slate-200 bg-white hover:bg-slate-50"}`}
              >
                <h3 className="text-lg font-black text-slate-900">{provider.name}</h3>
                <p className="mt-2 text-sm leading-6 text-slate-600">{provider.description}</p>
              </button>
            ))}
          </div>
          <div className="mt-8 rounded-xl border-2 border-blue-200 bg-blue-50 p-6">
            <p className="text-xs font-bold uppercase tracking-wider text-blue-700">Your Selection</p>
            <h3 className="mt-2 text-3xl font-black text-slate-900">{providerCards[selectedProvider].name}</h3>
            <p className="mt-3 text-sm leading-7 text-slate-700">{providerCards[selectedProvider].description}</p>
            <Link to="/help" className="mt-5 inline-flex rounded-lg bg-gradient-to-r from-blue-600 to-blue-700 px-6 py-3 text-sm font-bold text-white hover:shadow-lg transition">
              Request Quote Now
            </Link>
          </div>
        </div>
      </section>

      <section id="types" className="mx-auto max-w-7xl px-4 py-16 md:px-8">
        <div className="rounded-2xl bg-white p-8 shadow-lg border border-slate-100 md:p-12">
          <div className="inline-block rounded-full bg-blue-100 px-4 py-2 mb-3">
            <span className="text-xs font-bold uppercase tracking-wider text-blue-700">System Types</span>
          </div>
          <h2 className="mt-3 text-4xl font-black text-slate-900">Choose Your Solar System Type</h2>
          <p className="mt-4 text-slate-600 font-semibold max-w-2xl">Every property is unique. Here are the main system configurations we offer:</p>
          <div className="mt-8 grid gap-6 md:grid-cols-3">
            {systemTypes.map((item) => (
              <div key={item.title} className="rounded-xl bg-gradient-to-br from-blue-50 to-blue-100 p-6 border border-blue-200 hover:shadow-lg transition">
                <h3 className="text-lg font-black text-slate-900">{item.title}</h3>
                <p className="mt-3 text-sm leading-7 text-slate-700">{item.text}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section id="schemes" className="mx-auto max-w-7xl px-4 py-16 md:px-8">
        <div className="rounded-2xl bg-white p-8 shadow-lg border border-slate-100 md:p-12">
          <div className="inline-block rounded-full bg-blue-100 px-4 py-2 mb-3">
            <span className="text-xs font-bold uppercase tracking-wider text-blue-700">Billing Schemes</span>
          </div>
          <h2 className="mt-3 text-4xl font-black text-slate-900">Electricity Export & Billing Schemes</h2>
          <p className="mt-4 text-slate-600 font-semibold max-w-2xl">Choose the scheme that suits your property's energy profile:</p>
          <div className="mt-8 grid gap-6 lg:grid-cols-3">
            {schemeCards.map((item) => (
              <div key={item.title} className="rounded-xl border-2 border-slate-200 bg-white p-6 hover:border-blue-300 hover:shadow-lg transition">
                <h3 className="text-xl font-black text-slate-900">{item.title}</h3>
                <p className="mt-3 text-sm leading-7 text-slate-600">{item.text}</p>
                <div className="mt-5 rounded-lg bg-slate-50 p-3">
                  <p className="text-xs font-bold text-slate-700">Ideal for:</p>
                  <p className="text-sm font-semibold text-slate-700">{item.idealFor}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section id="faq" className="mx-auto max-w-7xl px-4 py-16 md:px-8">
        <div className="grid gap-8 lg:grid-cols-[0.95fr_1.05fr]">
          <div className="rounded-2xl bg-gradient-to-br from-blue-900 via-blue-800 to-blue-700 p-8 text-white shadow-xl">
            <div className="inline-block rounded-full bg-white/20 px-4 py-2 backdrop-blur-sm mb-4">
              <span className="text-xs font-bold uppercase tracking-wider text-white/90">Questions?</span>
            </div>
            <h2 className="mt-3 text-4xl font-black">Frequently Asked Questions</h2>
            <p className="mt-4 text-sm leading-7 text-white/90">
              Find answers to common solar installation and billing questions. Have a question we haven't covered? Contact our team for support.
            </p>
          </div>

          <div className="space-y-3">
            {faqItems.map(([question, answer]) => (
              <details key={question} className="rounded-xl border-2 border-slate-200 bg-white p-5 hover:border-blue-300 transition cursor-pointer group">
                <summary className="list-none text-sm font-black text-slate-900">
                  <div className="flex items-center justify-between">
                    <span>{question}</span>
                    <span className="text-blue-600 group-open:rotate-180 transition">▼</span>
                  </div>
                </summary>
                <p className="mt-4 text-sm leading-7 text-slate-700">{answer}</p>
              </details>
            ))}
          </div>
        </div>
      </section>

      <section className="mx-auto max-w-7xl px-4 py-16 md:px-8">
        <div className="rounded-2xl bg-white p-8 shadow-lg border border-slate-100 md:p-12">
          <div className="inline-block rounded-full bg-blue-100 px-4 py-2 mb-3">
            <span className="text-xs font-bold uppercase tracking-wider text-blue-700">Related Services</span>
          </div>
          <h2 className="mt-3 text-4xl font-black text-slate-900">Explore Our Other Services</h2>
          <p className="mt-4 text-slate-600 font-semibold">Complement your solar installation with our other property services:</p>
          <div className="mt-8 grid gap-6 md:grid-cols-2 xl:grid-cols-3">
            {relatedServices.map((item) => {
              const sharedClassName = "rounded-xl border-2 border-slate-200 p-6 text-left transition hover:border-blue-300 hover:shadow-lg bg-white";

              if (item.href.startsWith("#")) {
                return (
                  <a key={item.title} href={item.href} className={sharedClassName}>
                    <h3 className="text-lg font-black text-slate-900">{item.title}</h3>
                    <p className="mt-3 text-sm leading-7 text-slate-600">{item.text}</p>
                  </a>
                );
              }

              return (
                <Link key={item.title} to={item.href} className={sharedClassName}>
                  <h3 className="text-lg font-black text-slate-900">{item.title}</h3>
                  <p className="mt-3 text-sm leading-7 text-slate-600">{item.text}</p>
                </Link>
              );
            })}
          </div>
        </div>
      </section>

      <section className="mx-auto max-w-7xl px-4 py-16 md:px-8">
        <div className="rounded-2xl bg-white p-8 shadow-lg border border-slate-100 md:p-12">
          <div className="inline-block rounded-full bg-blue-100 px-4 py-2 mb-3">
            <span className="text-xs font-bold uppercase tracking-wider text-blue-700">Service Coverage</span>
          </div>
          <h2 className="mt-3 text-4xl font-black text-slate-900">Solar Services in Major Sri Lankan Cities</h2>
          <p className="mt-4 text-slate-600 font-semibold">Click your city to prefill the quote form:</p>
        <div className="mt-8 flex flex-wrap gap-3">
          {cities.map((city) => (
            <button
              key={city}
              type="button"
              onClick={() => {
                updateField("city", city);
                setStep(0);
                document.querySelector('form')?.scrollIntoView({ behavior: 'smooth' });
              }}
              className="rounded-full bg-gradient-to-r from-blue-100 to-blue-50 border-2 border-blue-200 px-5 py-2 text-sm font-bold text-blue-700 shadow-sm transition hover:border-blue-600 hover:shadow-md"
            >
              {city}
            </button>
          ))}
        </div>
        </div>
      </section>

      <section id="tips" className="bg-gradient-to-br from-blue-50 via-white to-slate-50">
        <div className="mx-auto max-w-7xl px-4 py-16 md:px-8">
          <div className="rounded-2xl bg-white p-8 shadow-lg border border-slate-100 md:p-12">
            <div className="inline-block rounded-full bg-blue-100 px-4 py-2 mb-3">
              <span className="text-xs font-bold uppercase tracking-wider text-blue-700">Solar Tips & Guides</span>
            </div>
            <h2 className="mt-3 text-4xl font-black text-slate-900">Tips for Switching to Solar Energy</h2>
            <p className="mt-4 text-slate-600 font-semibold">Learn about solar maintenance, efficiency, and best practices:</p>
            <div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">
              {tips.map((item, index) => (
                <button
                  key={item.title}
                  type="button"
                  onClick={() => setSelectedTip(index)}
                  className={`rounded-xl border-2 p-6 text-left transition font-semibold ${selectedTip === index ? "border-blue-600 bg-blue-50" : "border-slate-200 bg-white hover:border-blue-300 hover:bg-slate-50"}`}
                >
                  <h3 className="text-base font-black text-slate-900">{item.title}</h3>
                </button>
              ))}
            </div>

            <div className="mt-8 rounded-xl border-2 border-blue-200 bg-gradient-to-br from-blue-50 to-blue-100 p-8">
              <p className="text-xs font-bold uppercase tracking-wider text-blue-700">Selected Tip</p>
              <h3 className="mt-3 text-3xl font-black text-slate-900">{tips[selectedTip].title}</h3>
              <p className="mt-4 text-sm leading-7 text-slate-700 font-semibold">{tips[selectedTip].summary}</p>
            </div>
          </div>
        </div>
      </section>

      <section id="contact" className="mx-auto max-w-7xl px-4 py-16 md:px-8">
        <div className="grid gap-8 rounded-2xl bg-gradient-to-br from-blue-50 to-white p-8 shadow-lg border border-slate-100 lg:grid-cols-[0.95fr_1.05fr] lg:items-start md:p-12">
          <div className="rounded-2xl bg-gradient-to-br from-blue-900 via-blue-800 to-slate-900 p-8 text-white">
            <div className="inline-block rounded-full bg-white/20 px-4 py-2 backdrop-blur-sm mb-4">
              <span className="text-xs font-bold uppercase tracking-wider text-white/90">Get in Touch</span>
            </div>
            <h2 className="mt-3 text-4xl font-black">Contact Our Solar Team</h2>
            <p className="mt-4 text-sm leading-7 text-white/90">Have questions about solar installation, quotes, or financing? Our expert team is here to help you find the perfect solution for your property.</p>
          </div>

          <div className="grid gap-4 md:grid-cols-2">
            <div className="rounded-xl bg-white border-2 border-slate-200 p-6 shadow-sm hover:shadow-md transition">
              <p className="text-xs font-bold uppercase tracking-wider text-blue-700">Phone</p>
              <p className="mt-3 text-sm font-bold text-slate-900">(+94) 11 7 167 167</p>
              <p className="text-sm font-bold text-slate-900">(+94) 76 7 167 167</p>
            </div>
            <div className="rounded-xl bg-white border-2 border-slate-200 p-6 shadow-sm hover:shadow-md transition">
              <p className="text-xs font-bold uppercase tracking-wider text-blue-700">Email</p>
              <p className="mt-3 text-sm font-bold text-slate-900">contactus@lankapropertyweb.com</p>
            </div>
            <div className="rounded-xl bg-white border-2 border-slate-200 p-6 shadow-sm md:col-span-2 hover:shadow-md transition">
              <p className="text-xs font-bold uppercase tracking-wider text-blue-700">Newsletter</p>
              <div className="mt-3 flex flex-col gap-3 sm:flex-row">
                <input className="flex-1 rounded-lg border border-slate-300 px-4 py-3 text-sm font-medium outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-200" placeholder="Your email address" />
                <Link to="/help" className="rounded-lg bg-gradient-to-r from-blue-600 to-blue-700 px-6 py-3 text-center text-sm font-bold text-white hover:shadow-lg transition">
                  Contact Us
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="mx-auto max-w-7xl px-4 pb-12 md:px-8">
        <div className="rounded-2xl bg-white p-8 text-sm leading-8 text-slate-700 shadow-lg border border-slate-100 md:p-12">
          <div className="inline-block rounded-full bg-blue-100 px-4 py-2 mb-4">
            <span className="text-xs font-bold uppercase tracking-wider text-blue-700">About Solar Energy</span>
          </div>
          <h2 className="mt-4 text-2xl font-black text-slate-900">Going Green with Solar Power</h2>
          <p className="mt-4">
            Solar panels for homes convert sunlight into clean electricity, helping homeowners reduce electricity bills and their environmental footprint. Industrial solar systems can reduce operational costs significantly while improving your sustainability profile and market value.
          </p>
          <p className="mt-4">
            By comparing providers, system types, and financing options through our platform, you can make an informed decision and find the solar solution that perfectly fits your property, budget, and energy needs.
          </p>
          <div className="mt-6 flex flex-wrap gap-3">
            <Link to="/" className="inline-flex rounded-lg bg-gradient-to-r from-blue-600 to-blue-700 px-6 py-3 text-sm font-bold text-white hover:shadow-lg transition">
              Back to Home
            </Link>
            <Link to="/our-services" className="inline-flex rounded-lg border-2 border-blue-300 bg-white px-6 py-3 text-sm font-bold text-blue-700 hover:bg-blue-50 transition">
              View All Services
            </Link>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
}